# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^(docs/|initial_data_formation/|src/settings/|src/bot/handlers/notion_parse/)
      - id: trailing-whitespace
        exclude: ^(docs/|initial_data_formation/|src/settings/|src/bot/handlers/notion_parse/)
      - id: check-docstring-first
        exclude: ^(docs/|initial_data_formation/|src/settings/|src/bot/handlers/notion_parse/)
      - id: check-merge-conflict
        exclude: ^(docs/|initial_data_formation/|src/settings/|src/bot/handlers/notion_parse/)
      - id: mixed-line-ending
        exclude: ^(docs/|initial_data_formation/|src/settings/|src/bot/handlers/notion_parse/)
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.11.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        exclude: ^(docs/|src/bot/hegai_db/|initial_data_formation/|src/settings/|src/bot/handlers/notion_parse/)
  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.4
    hooks:
      - id: pylint
        exclude: ^(docs/|src/bot/hegai_db/|initial_data_formation/|src/settings/|src/bot/handlers/notion_parse/)
